### ISSUE TITLE
Doesn't work inside iframe

### ISSUE THREAD

**Issue by gabrielmaldi** [mattcdowning/nomailto#1]
Thanks for building this! I just installed it and I'm already loving it.

I found that it doesn't work when `mailto:` is inside an `iframe`, check out this [fiddle](https://jsfiddle.net/gabrielmaldi/vr33remq/).

**Comment by aaronjmccoy** [comment]
Looks like that's a security issue; iframes with different domains as sources can't have their contents accessed for security reasons. Since the iframe there references a domain that's different from jfiddle's it won't work.

http://stackoverflow.com/questions/6316979/selecting-an-element-in-iframe-jquery

Working from that knowledge.

**Comment by mattcdowning** [comment]
Unless someone knows more about iframes than we do, I'm going to close this issue.

**Comment by jeroen1322** [comment]
As far as I know, you can only modify current DOM on page load. Because iFrame is another DOM, that could not be modified. The plugin runs in the current DOM, so that could explain it.
